server {
    listen 80;
    root /var/www/html;
    index index.php index.html;
    client_max_body_size 30M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    location ~ /\.env {
        deny all;
        return 403; # Or 404
    }

	# Deny access to .env files
    location ~ /\.redirects {
        deny all;
        return 403; # Or 404
    }

    # Deny access to other hidden files/directories (optional, but good practice)
    location ~ /\.(ht|svn|bash|cvs) {
        deny all;
        return 403;
    }

    location /api/ {
        try_files $uri $uri/ /api/games/index.php?$args;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param REQUEST_METHOD $request_method;
    }


    	rewrite ^/api/games/([a-z0-9-_]+)/$ /api/games/index.php?id=$1 last;
    	rewrite ^/api/plataformas/([a-z0-9-_]+)/$ /api/plataformas/index.php?id=$1 last;
        rewrite ^/api/consolas/([a-z0-9-_]+)/$ /api/consolas/index.php?id=$1 last;
        rewrite ^/api/imagenes/([a-z0-9-_]+)/$ /api/imagenes/index.php?id=$1 last;


}
